name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.14.0"

      - name: Install dependencies
        run: npm install

      - name: Clean dist folder
        run: rm -rf dist/*

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Create Release
        id: create_release
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh release create "v1.0.0" dist/**/* --title "Release v1.0.0" --notes "Automated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
