name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14.0"

      - name: Install dependencies
        run: npm install

      - name: Clean dist folder
        run: rm -rf dist/*

      - name: Build the project
        run: npm run build

      - name: List dist directory
        run: ls -la dist

      - name: Run tests
        run: npm test

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create Release
        id: create_release
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          gh release create "v1.0.0" dist/*.js .env .gitignore --title "Release v1.0.0" --notes "Automated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
