name: Node.js CI with TypeScript

on:
  push:
    branches: ["main"]

env:
  build-number: ${{ github.run_number }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}

      - name: run tests
        run: npm run test

      - name: Package app
        run: |
          mkdir outCode
          cp -R dist/* outCode/

          cp package.json outCode/
          cp jest.config.js outCode/
          cp package-lock.json outCode/
          cp tsconfig.json outCode/

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release ${{ env.build-number }}"
          files: |
            outCode/**
