name: Node CI Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: maharnackademin/devopsbackend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Deploy to production
      #   uses: johnbeynon/render-deploy-action@v0.0.8
      #   with:
      #     # https://api.render.com/deploy/srv-crp71ku8ii6s73cd0gj0?key=i0sE4jP_63s
      #     service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
      #     api-key: ${{ secrets.MY_RENDER_API_KEY }}
      #     wait-for-success: false
