name: Node CI Docker image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build Docker image
        run: |
          docker build -t nodebackend .

      - name: Tag Docker image
        run: |
          docker tag nodebackend maharnackademin/nodebackend:latest

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push maharnackademin/nodebackend:latest

      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

      # - name: Deploy to production
      #   uses: johnbeynon/render-deploy-action@v0.0.8
      #   with:
      #     service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
      #     api-key: ${{ secrets.MY_RENDER_API_KEY }}
      #     wait-for-success: false
